### ISSUE TITLE
Shortcut for referring to group name

### ISSUE THREAD

**Issue by samuelweiler** [w3c/horizontal-issue-tracker#13]
In rewriting the text of the tracker page, I want to be able to refer to the name of the group, not just the URL of their tracker.   May I have a macro for that, please?

**Comment by samuelweiler** [comment]
Amazingly, this is the feature I most want, because I want to clean up the wrapper text.

**Comment by plehegar** [comment]
Making sure I understand what's being asked. You want a short to refer to an horizontal tool in the text of the review comment tracker page. correct?

**Comment by samuelweiler** [comment]
I want to be able to replace the title and/or header text e.g.

> This page tracks comments made by the Group on the specs of other WGs. It only shows tracker issues the Group has not closed. (Issues may remain open in the Group tracker even if closed by the other WG in their repo.)

with

> ...  made by PING on the specs of other WGs. ..."

**Comment by plehegar** [comment]
This has been done.
