### ISSUE TITLE
Document update frequency

### ISSUE THREAD

**Issue by samuelweiler** [w3c/horizontal-issue-tracker#14]
tracker page should explain how quickly tracker updates.  (e.g. if I add a WG label to a manually-created issue in a tracker repo, how long before this tool picks it up?)

**Comment by plehegar** [comment]
Noted. Right, the tool is ran manually once a day around 9am ET.

**Comment by samuelweiler** [comment]
Reiterating this request - I want the answer to be easy to find, even if we don't yet like the answer.  PR drafted.

**Comment by plehegar** [comment]
Fixed in
 https://github.com/w3c/horizontal-issue-tracker/commit/0df4b5d032c7ee6bb370d61e232f2413785de680
