### ISSUE TITLE
Automate running of the tool

### ISSUE THREAD

**Issue by samuelweiler** [w3c/horizontal-issue-tracker#30]
Is it time to automate running the tool?  I'm seeing issues get closed between being labeled and the tool running (e.g. https://github.com/w3c/horizontal-issue-tracker/issues/9), and running it more often might help.  (If we do this, we need to update https://github.com/w3c/horizontal-issue-tracker/issues/14 and https://github.com/w3c/horizontal-issue-tracker/pull/29 )

**Comment by plehegar** [comment]
The fix for this is in https://github.com/w3c/horizontal-issue-tracker/commit/4ac4230f01c76aaa2300b15c0b30447b6aeb99ea
It should be deployed tomorrow (once yesterday issues with the GH cache are cleared)

**Comment by plehegar** [comment]
Deployed in production.
