### ISSUE TITLE
No label for `wg:w3ctag`

### ISSUE THREAD

**Issue by aphillips** [w3c/horizontal-issue-tracker#42]
I was reviewing [this document](https://www.w3.org/TR/2024/DNOTE-ethical-web-principles-20240319) and noticed that TAG's documents don't get `s:` labels in my repo automagically nor is there a WG label for the TAG. TAG is "special" but should be instrumented just like other groups for horizontal review, no?

**Comment by plehegar** [comment]
This is not the tag you're looking for since the TAG is not a WG.

You're looking for https://github.com/w3c/i18n-activity/issues?q=is%3Aopen+is%3Aissue+label%3Aother%3Atag
